LSSTDESC/firecrown

.circleci/config.yml
README.md
bin/firecrown
dev-requirements.txt
examples/cosmicshear.yaml
examples/generate_cosmicshear_data.py
firecrown/__init__.py
firecrown/cosmosis/__init__.py
firecrown/cosmosis/api.py
firecrown/cosmosis/interface.py
firecrown/cosmosis/run.py
firecrown/loglike.py
firecrown/parser.py
firecrown/tests/test_cosmosis.py

This PR re-enables the interface of FireCrown to the CosmoSIS samplers.
Sampling with most of them will now work using `firecrown sample file.yaml`
Everything cosmosis-related is in the cosmosis subdirectory, and I've simplified it a bit since the previous version.  If you don't have cosmosis installed the other stuff will still work.
Also I changed from sigma_8 to A_s in the examples, since the latter is the official parameter of DESC.
On a separate note - we should disable flake8 in the CI.  It will put off too many potential contributors.
Closes #30

Cosmosis interface

---

firecrown/analysis/emcee_interface.py
firecrown/analysis/tests/test_emcee_interface.py

This PR makes sure the output from emcee is converted to a python scalar in the parameters so that the output YAML is nice to look at.

BUG make sure to convert to python scalars

---

.circleci/config.yml
firecrown/ccl/likelihoods/gaussian.py
firecrown/ccl/likelihoods/tdist.py
firecrown/ccl/likelihoods/tests/conftest.py
firecrown/ccl/statistics/tests/test_two_point.py
firecrown/ccl/statistics/two_point.py
firecrown/tests/test_integration_with_cuts.py

This PR adds bin limit and generation options for 2pt stats. The API is
```yaml
ell_or_theta_min: 10
ell_or_theta_max: 100
ell_or_theta:
min: 10
max: 1000
n: 10
binning: 'log'
```
These are extra options to any 2pt stat in the config file.
This PR also renames the old ell_min, etc options to a new block `ell_for_xi` which has keys `min`, `max`, `mid`, `n_log` matching the options in CCL.

ENH add ell or theta range for 2pt stats and other binning options

---

firecrown/ccl/two_point.py

augur was crashing, because if two_point.compute_likelihood was called and `likelihood` was not in data, then `measured` variable was not on return statement.

Fix to bug with undefined measured when likelihood not in data

---

.github/workflows/ci.yml
environment.yml
firecrown/connector/cobaya/likelihood.py
firecrown/connector/cosmosis/likelihood.py
firecrown/likelihood/gauss_family/gauss_family.py
firecrown/likelihood/gauss_family/gaussian.py
firecrown/likelihood/gauss_family/statistic/source/number_counts.py
firecrown/likelihood/gauss_family/statistic/source/source.py
firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
firecrown/likelihood/gauss_family/statistic/statistic.py
firecrown/likelihood/gauss_family/statistic/supernova.py
firecrown/likelihood/gauss_family/statistic/two_point.py
firecrown/likelihood/gauss_family/student_t.py
firecrown/likelihood/likelihood.py
firecrown/parameters.py
firecrown/updatable.py
pylintrc_for_tests
tests/likelihood/lkdir/lkmodule.py
tests/likelihood/lkdir/lkscript.py
tests/likelihood/test_likelihood.py
tests/test_descriptors.py
tests/test_parameters.py
tests/test_updatable.py

Added testing and fixed pylint issues (old and new) on tests (including a pylintrc for tests and its inclusion on GHA).

Added state control for updatable objects. 

---

examples/srd_sn/README.md
examples/srd_sn/generate_sn_data.py

User can now use two different styles of Hubble diagram (HD) as input. 
1. The default `cosmoMC` styled HD 
2. LSST DESC's HD with new file structure. 
Either of them can be now passed as argument by the user.

Additional option to read DESC Formatted Hubble diagram data file

---

firecrown/connector/mapping.py

The current use of `require_nonlinear_pk` breaks the existing 3x2pt setups that are using the `star_challenge` branch. 
This PR changes `require_nonlinear_pk==True` from "Don't use any non-linear P(k), neither from CAMB nor from CCL" to "If not provided by CAMB, compute the non-linear power spectrum in CCL". To me this make more sense for the name of the file.
`require_nonlinear_pk==False` still behaves the same when CAMB doesn't produce non-linear P(k).

Change logic of require_nonlinear_pk

---

firecrown/likelihood/likelihood.py

If a likelihood raises a `FileNotFoundError`, for example due to a missing `sacc` file, that exception gets reraised as an `ImportError` with the likelihood file name and buries the actual missing file way up in the trace. See #173 and #175.
This PR removes the `try...except` block around `spec.load.exec_module`. `FileNotFoundError` now gets passed through correctly. If the actual module cannot be found, that still raises an informative exception.

Pass FileNotFoundError exceptions in likelihood through

---

examples/des_y1_3x2pt/des_y1_3x2pt.py
examples/srd_sn/sn_srd_values.ini
examples/srd_sn/sn_srd_values_planck_bao.ini
examples/srd_sn/snonly_values.ini
firecrown/connector/cosmosis/likelihood.py
firecrown/likelihood/gauss_family/gauss_family.py
firecrown/likelihood/gauss_family/gaussian.py
firecrown/likelihood/gauss_family/statistic/source/number_counts.py
firecrown/likelihood/gauss_family/statistic/source/source.py
firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
firecrown/likelihood/gauss_family/statistic/supernova.py
firecrown/likelihood/gauss_family/statistic/two_point.py
firecrown/likelihood/gauss_family/student_t.py
firecrown/parameters.py
firecrown/updatable.py
tests/likelihood/lkdir/lkmodule.py
tests/test_updatable.py

This adds optional default parameters to `ParamsMap.get_from_prefix_param`. This is motivated by issue #193, which could have been avoided by having default values in the code, rather than some ini file.
Before merging, the correct value for `alphag` needs to be confirmed though.

Allow default parameter values

---

.flake8
firecrown/connector/cosmosis/likelihood.py
setup.cfg
tests/connector/cosmosis/test_cosmosis_module.py
tests/test_parameters.py
tests/test_updatable.py

This fixes issue #211 by making the configuration parameter "sampling_parameters_sections" be optional, with a default value that is an empty string.

211 cosmosis connector fails if sampling parameters sections is not present on the likelihood configuration

---

firecrown/likelihood/gauss_family/statistic/source/number_counts.py
firecrown/likelihood/gauss_family/statistic/two_point.py
firecrown/likelihood/likelihood.py
firecrown/parameters.py

This fixes two real bugs and addresses many minor issues reported by `pylint` or `mypy`.

217 more pylint cleanup

---

examples/des_y1_3x2pt/cobaya_evaluate.yaml
examples/des_y1_3x2pt/des_y1_3x2pt.py
examples/des_y1_3x2pt/des_y1_3x2pt_PT_values.ini
examples/des_y1_3x2pt/des_y1_3x2pt_values.ini

The des 3x2pt example configurations still had the `alphag` parameter specified to the non-standard -1. Since this parameter is non-standard anyway and is covered by the correct default, these can be removed from the example.

Remove obscure (and wrong) alphag parameter from examples

---

.github/workflows/ci.yml
environment.yml

This commit changes environment.yml to use the environment name `firecrown_developer`, and adjusts CI accordingly.

Use correct environment name in installation

---

.gitignore
docs/developer_installation.rst
tutorial/development_example.qmd
tutorial/introduction_to_firecrown.qmd

This pull request updates the documentation with the correct instructions for creating the conda environment for firecrown development.

Tutorial instructions for creating conda environment are incorrect

---

.github/workflows/ci.yml
examples/des_y1_3x2pt/des_y1_cosmic_shear_TATT.py
firecrown/connector/cobaya/ccl.py
firecrown/connector/mapping.py
firecrown/connector/numcosmo/numcosmo.py
firecrown/likelihood/gauss_family/gauss_family.py
firecrown/likelihood/gauss_family/statistic/source/number_counts.py
firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
firecrown/likelihood/gauss_family/statistic/supernova.py
firecrown/likelihood/gauss_family/statistic/two_point.py
firecrown/likelihood/gauss_family/student_t.py
firecrown/utils.py
pylintrc

Make pylint more permissive about most names

---

examples/des_y1_3x2pt/.gitignore
examples/des_y1_3x2pt/des_y1_3x2pt_PT.py
examples/des_y1_3x2pt/des_y1_cosmic_shear_TATT.py

This fixes the issue by creating the figure in the current directory, which was simpler than creating a subdirectory.

Create figure in current directory

---

.github/workflows/ci.yml
docs/conf.py
docs/developer_installation.rst
firecrown/likelihood/gauss_family/gauss_family.py
firecrown/likelihood/gauss_family/statistic/statistic.py
tests/likelihood/gauss_family/test_student_t.py

This PR introduces a very simple state machine to ensure that methods are called in the right order.

Assure that gaussfamily likelihoods have methods called in the right order

---

.github/workflows/ci.yml
examples/cluster_number_counts/cluster_redshift_richness.py
examples/cluster_number_counts/compare_integration_methods.py
firecrown/likelihood/gauss_family/statistic/binned_cluster_number_counts.py
firecrown/models/cluster/abundance.py
firecrown/models/cluster/binning.py
firecrown/models/cluster/integrator/integrator.py
firecrown/models/cluster/integrator/numcosmo_integrator.py
firecrown/models/cluster/integrator/scipy_integrator.py
firecrown/models/cluster/kernel.py
firecrown/models/cluster/mass_proxy.py
firecrown/models/cluster/recipes/cluster_recipe.py
firecrown/models/cluster/recipes/murata_binned_spec_z.py
firecrown/models/cluster/recipes/murata_unbinned_spec_z.py
firecrown/models/cluster/recipes/true_mass_spec_z.py
firecrown/models/pylintrc
pylint_plugins/README.md
pylint_plugins/duplicate_code.py
pylintrc
tests/cluster_recipes/test_murata_binned_spec_z.py
tests/cluster_recipes/test_murata_unbinned_spec_z.py
tests/conftest.py
tests/likelihood/gauss_family/statistic/test_cluster_number_counts.py
tests/pylintrc
tests/test_cluster_abundance.py
tests/test_cluster_binning.py
tests/test_cluster_integrators.py
tests/test_cluster_kernels.py
tests/test_cluster_mass_richness.py

This PR changes the cluster number counts likelihood workflow to support potentially more complex integrands.
* Removed the `Kernel` abstract class and concept of a shared interface between components of the integrand. 
* The abstraction that this introduces doesn't fit well with the use case of kernels that may take an arbitrary number of arguments.
* This includes removing the automated integrand building code from `ClusterAbundance`.  The responsibility of assembling the integrand for the cluster number counts is now placed on the user in the form of `ClusterRecipe`
* Added `cluster_recipe` module.  This is where users can assemble a cluster number counts integrand using the pieces in firecrown.models.cluster
* Updated the statistic to accept a cluster recipe. 
* Each cluster recipe …

Refactoring the integration / integrand workflow in the cluster count calculation

---

firecrown/likelihood/gauss_family/gauss_family.py

Right now `get_cov` can't get called after the theory has been computed.

Allow calling get_cov when in State.COMPUTED

---

codecov.yml

Removing the `branches` option from our `codecov.yml` configuration to re-enable status checks on PRs.
After speaking with support, this option specifies which **source branches** will trigger status checks, **not target branches**.  
For example, I assumed `branches: [master]` meant, “A PR from any branch into master will trigger codecov status checks”.  However it really means “A PR from master into any other branch will trigger status checks”.
While I find this option sort of strange, since conventionally one wouldnt PR from master into any other branch, removing the branches config value from my patch and project sections completely fixed the issue.

Re-adding codecov status checks to PRs.

---

docs/conf.py
docs/environment.yml
environment.yml

Fixing readthedocs PDF build step

---

firecrown/likelihood/gauss_family/gauss_family.py
firecrown/utils.py
tests/likelihood/gauss_family/test_const_gaussian.py
tests/test_utils.py

This PR factors out functionality in `make_realization` into a new `GaussFamiliy.get_sacc_indices` method and a `save_to_sacc` function for easier handling of sacc objects. For example, for blinding we need to write a modified data vector back to a sacc file.
Usage:
```python
idx = likelihood.get_indices()
new_sacc = save_to_sacc(
sacc_data=sacc_data,
data_vector=new_data_vector,
indices=idx,
strict=True,
)
```
TODO: ~~add tests~~

Add a save_to_sacc utility function

---

docs/contrib.rst

This updates the contribution guidelines to describe the policy we are applying to PRs for firecrown.

Update contribution guidelines

---

tests/test_bug398.py

Adding validation tests for TwoPoint compute_theory_vector with a window function.
- The benchmark was computed using v1.6.0 and agrees with versions 1.5.0 -- 1.8.0a. 
- For version 1.5.0 the used pyccl was 2.8.0 and the tests agree with larger relative difference (~1.0e-4). 
- The other versions agree with better relative difference (~1.0e-8).

Validation tests for TwoPoint window 

---

.github/workflows/ci.yml
examples/cluster_number_counts/compare_integration_methods.py
examples/des_y1_3x2pt/generate_des_data.py

Under Python 3.12 with the newest version of flake8, we have several complaints about missing whitespace around operators. This PR fixes those complaints.

Fix flake8 whitespace complaints

---

docs/environment.yml
environment.yml

This releases most of our version restrictions on dependencies, because they have become obsolete.
We are still restricting the version of Sphinx because newer versions do not work for LaTeX/pdf generation.

Release most version restrictions

---

firecrown/likelihood/two_point.py
tests/conftest.py
tests/likelihood/gauss_family/statistic/test_two_point.py

Create test and fix for issue 427

---

examples/des_y1_3x2pt/des_y1_3x2pt_PT.py
firecrown/updatable.py

This contains a few more updates to doscstrings.
It also contains a fix for the graphing part of the `des_y1_3x2pt_PT.py` example, which is not run in CI.

Even more docstrings updates

---

firecrown/likelihood/number_counts.py
firecrown/likelihood/source.py
firecrown/likelihood/statistic.py
firecrown/likelihood/student_t.py
firecrown/likelihood/supernova.py

This updates more docstrings (and a few type annotations).

Again more docstrings

---

firecrown/models/pylintrc
pylintrc

This tweaks the necessary pylintrc files to avoid failures due to new warnings from pylint 3.3.

Temporary tweaks to fix CI failures from pylint 3.3

---

.github/pull_request_template.md
.github/workflows/ci.yml
firecrown/likelihood/number_counts.py
firecrown/likelihood/source.py
firecrown/likelihood/statistic.py
firecrown/likelihood/two_point.py
firecrown/models/two_point.py
firecrown/parameters.py
firecrown/updatable.py
tests/conftest.py
tests/likelihood/gauss_family/statistic/source/test_source.py
tests/likelihood/gauss_family/statistic/test_two_point.py
tests/test_bug_413.py
tests/test_models_twopoint.py

Please include a summary of the change(s). Include  which issue is fixed, if this is a bug fix.
Please also include relevant motivation and context. List any new dependencies that are required for this
change.
Fixes # (issue)
Discussion: # (link)
* Refactoring
* Breaking change (fix or feature that would cause existing functionality to not work as expected)
This refactoring contains possible breaking changes because it changes the internal data of `TwoPoint`, and those internal data are not hidden from users.

Move twopoint theory

---

firecrown/parameters.py
tests/likelihood/gauss_family/statistic/source/test_source.py
tests/test_parameters.py
tests/test_pt_systematics.py

This PR introduces additional testing to cover previously untested code.
* Refactoring

Add test for nc.LinearBiasSystematic

---

.github/workflows/ci.yml

Adding conda-remove-defaults: true to conda CI options.
This assures that the defaults conda channel will not be used.

Adding conda-remove-defaults: true to conda CI options.

---

firecrown/connector/cobaya/ccl.py
firecrown/connector/mapping.py
firecrown/connector/numcosmo/numcosmo.py
firecrown/data_functions.py
firecrown/generators/two_point.py
firecrown/likelihood/gaussfamily.py
firecrown/likelihood/likelihood.py
firecrown/likelihood/supernova.py
firecrown/likelihood/two_point.py
firecrown/models/cluster/abundance.py
firecrown/models/cluster/kernel.py
firecrown/utils.py
tests/cluster_recipes/test_murata_binned_spec_z.py
tests/conftest.py
tests/likelihood/gauss_family/statistic/test_two_point.py
tests/metadata/test_metadata_two_point.py
tests/metadata/test_metadata_two_point_measurement.py
tests/metadata/test_metadata_two_point_sacc.py
tests/test_ccl_factory.py
tests/test_cluster_abundance.py
tests/test_cluster_integrators.py
tests/test_cluster_kernels.py
tests/test_cluster_mass_richness.py

Update type hints for compatibility with NumPy 2.x
More type-hints and numpy array explicit conversions to satisfy mypy and numpy 2.x.

Update type hints for compatibility with NumPy 2.x

---

.github/workflows/ci.yml
firecrown/ccl_factory.py
firecrown/connector/cobaya/likelihood.py
firecrown/connector/cosmosis/likelihood.py
firecrown/connector/mapping.py
firecrown/connector/numcosmo/helpers.py
firecrown/connector/numcosmo/numcosmo.py
firecrown/data_functions.py
firecrown/likelihood/factories.py
firecrown/likelihood/two_point.py
firecrown/updatable.py
firecrown/utils.py
pyproject.toml
tests/connector/numcosmo/test_numcosmo_mapping.py
tests/connector/test_mapping.py
tests/generators/test_two_point_generatory.py
tests/likelihood/test_factories.py
tests/test_data_functions.py
tests/test_updatable.py
tests/test_utils.py

This PR provides commits to improve the branch coverage of the test suite.
It also activates the pytest measurement of branch coverage.
* Refactoring

Fix branch coverage

---

.github/workflows/ci.yml
firecrown/likelihood/source_factories.py
firecrown/metadata_types.py
tests/conftest.py
tests/likelihood/gauss_family/statistic/test_two_point.py
tests/metadata/test_metadata_two_point_types.py

This renames the enumeration values Galaxies.SHEAR_MINUS and Galaxies.SHEAR_PLUS to Galaxies.PART_OF_XI_MINUS and Galaxies.PART_OF_XI_PLUS throughout. The old names are left in place as aliases for backwards compatibility of existing code that is using the old names. New code should use the new names.
Fixes #509
* New feature (non-breaking change which adds functionality)

Change SHEAR_MINUS/PLUS to PART_OF_XI_MINUS/PLUS

---

environment.yml
firecrown/ccl_factory.py
tests/likelihood/gauss_family/statistic/test_two_point.py
tests/metadata/test_metadata_two_point_sacc.py

This will work when/if the PR for SACC backward compatibility is accepted and a new release is made.
A few warning messages were updated in the new SACC version. This PR updates them so the tests can run. This makes firecrown required new SACC version. 
* Bug fix (non-breaking change which fixes an issue)

Minor updates to make firecrown tests run with SACC 1.0.

---

.github/workflows/ci.yml

This adds the running of Smokescreen's tests, in their latest tagged version, to Firecrown CI.
* New workflow job in CI

Add running Smokescreen tests to CI

---

.github/workflows/ci.yml

This PR simplifies the `ci.yml` that configures our CI workflows.
The result should be easier maintenance with no degradation of the speed of the testing.

Simplify workflows

---

.github/workflows/ci.yml
environment.yml

The `isitgr` package fails to load on macOS runs due to duplicated RPATH entries in its binary. This PR applies the necessary steps to remove the extra entry. The issue appears to occur only on CI, as we could not reproduce it locally.
* Bug fix (non-breaking change which fixes an issue)

Debugging isitgr loading in CI.

---

tests/metadata/test_metadata_two_point_types.py

mypy 1.18.1 is complaining about comparison of Enum aliases using `is`.
The use of `is` is actually correct, but since mypy is now complaining about it, this PR changes the test to use `==` instead.
* Bug fix (non-breaking change which fixes an issue)

Alter test to avoid mypy error

---

tests/test_ccl_factory.py

This PR modifies fixtures in test_ccl_factory.py to reduce the number of skips. This reduces the number of skips due to "CAMB extra parameters are only compatible with PUR_CCL_MODE from > 380 to 0..
* Refactoring

Rework fixtures to avoid skips
