- .circleci/config.yml
- .gitignore
- bin/firecrown
- firecrown/metadata.py
- firecrown/tests/test_metadata.py
This PR adds code for writing run metadata.
Closes #32
> ENH run metadata

- firecrown/ccl/sources/sources.py
This PR renames _nz to make it more descriptive.
> STY rename _nz

- firecrown/ccl/sources/sources.py
- firecrown/ccl/sources/tests/test_lss_source.py
This PR adds an LSS source. 
Closes #41
> ENH added an LSS source

- firecrown/ccl/systematics/lss.py
- firecrown/ccl/systematics/tests/test_lss.py
This PR adds a linear bias systematic.
Closes #40
> ENH added linear bias

- firecrown/ccl/statistics/tests/test_two_point.py
- firecrown/ccl/statistics/two_point.py
This PR adds real-space two-point computations.
Closes #38
> ENH added real-space computations

- firecrown/ccl/systematics/tests/test_wl.py
- firecrown/ccl/systematics/wl.py
This PR adds a linear IA systematic. 
Closes #27
> ENH add linear IA systematic

- bin/firecrown
- firecrown/io.py
- firecrown/tests/test_io.py
> ENH added i/o stuff

- firecrown/ccl/systematics/lss.py
- firecrown/ccl/systematics/tests/test_lss.py
Implement magnification bias model (resolves #51).
> Magnification bias

- firecrown/ccl/statistics/two_point.py
- firecrown/cosmology.py
The caches are using a lot of memory. Let's use less of them.
> cache less, compute more

- .circleci/config.yml
- API.md
- examples/cosmicshear/cosmicshear.yaml
- examples/cosmicshear/generate_cosmicshear_data.py
- firecrown/ccl/core.py
- firecrown/ccl/likelihoods/gaussian.py
- firecrown/ccl/likelihoods/tdist.py
- firecrown/ccl/likelihoods/tests/conftest.py
- firecrown/ccl/likelihoods/tests/test_gaussian.py
- firecrown/ccl/likelihoods/tests/test_tdist.py
- firecrown/ccl/parser.py
- firecrown/ccl/sources/sources.py
- firecrown/ccl/sources/tests/test_lss_source.py
- firecrown/ccl/sources/tests/test_wl_source.py
- firecrown/ccl/statistics/tests/test_two_point.py
- firecrown/ccl/statistics/two_point.py
- firecrown/ccl/two_point.py
- firecrown/tests/test_integration.py
- requirements.txt
- setup.cfg
This PR converts the library to use SACC only.
> ENH interface with SACC

- API.md
- bin/firecrown
- firecrown/ccl/sources/sources.py
- firecrown/ccl/two_point.py
- firecrown/io.py
- firecrown/parser.py
- firecrown/tests/test_integration.py
- firecrown/tests/test_io.py
This PR uses SACC for outputs.
> ENH first pass at SACC outputs

- .gitignore
- firecrown/ccl/two_point.py
- firecrown/tests/test_integration.py
This PR allows the systematics section of the configs for CCL to be optional.
Closes #77
> BUG make systematics section optional

- API.md
- examples/cosmicshear/cosmicshear.yaml
- examples/des_y1_3x2pt/des_y1_3x2pt.yaml
- examples/desc_srd_v1/srd_v1_gen.yaml
- examples/desc_srd_v1/srd_v1_model.yaml
- firecrown/ccl/two_point.py
- firecrown/parser.py
- firecrown/tests/test_integration.py
This PR enables in-memory SACC files and configs.
closes #78
> ENH enable in memory stuff

- firecrown/ccl/likelihoods/gaussian.py
- firecrown/ccl/likelihoods/tdist.py
- firecrown/ccl/likelihoods/tests/test_gaussian.py
- firecrown/ccl/likelihoods/tests/test_tdist.py
> ENH allow all kinds of covariances

- examples/cosmosis/cosmodc2_firecrown_real_fisher.yaml
This PR removes the one output for cosmosis specified in YAML I could find. cc @slosar @chihway
> DOC fix example outputs

- README.md
> DOC add a bit

- .circleci/config.yml
> removed old bin/firecrown from flake8 test.

- docs/diagrams/GNUmakefile
- docs/diagrams/gaussian-family.puml
- docs/diagrams/likelihood.puml
- docs/diagrams/statistic.puml
- docs/diagrams/twopoint.puml
- docs/diagrams/updatable.puml
- docs/diagrams/updatable_frag.iuml
- firecrown/parameters.py
- firecrown/updatable.py
- tests/test_parameters.py
- tests/test_updatable.py
* Change Updateable to Updatable in diagrams
* Make RequiredParameters more immutable
* Add unit testing for Updatable and RequiredParameters
> Several design review issues

- firecrown/connector/cosmosis/likelihood.py
- firecrown/connector/mapping.py
> Move method calculate_ccl_args

- docs/Makefile
- docs/conf.py
- docs/diagrams/GNUmakefile
- docs/index.rst
- firecrown/connector/cobaya/ccl.py
- firecrown/connector/cosmosis/likelihood.py
- firecrown/likelihood/gauss_family/gauss_family.py
- firecrown/likelihood/gauss_family/gaussian.py
- firecrown/likelihood/gauss_family/statistic/source/source.py
- firecrown/likelihood/gauss_family/statistic/statistic.py
- firecrown/likelihood/gauss_family/statistic/supernova.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
- firecrown/likelihood/gauss_family/student_t.py
- firecrown/likelihood/likelihood.py
- firecrown/updatable.py
- firecrown/version.py
It needs several tweaks and all the static documentation.
> First version of Sphinx support. 

- .gitignore
- README.md
- docs/index.rst
This addresses (at least in a preliminary fashion) the items in issue #164 . It will require updating when we deploy the new documentation to read-the-docs. It will also require updating when we are fully conformant to pylint.
More importantly, it will require updating when we have better unit testing in place.
> 164 modest updates to readme to make the repo more accessible

- firecrown/descriptors.py
- firecrown/parameters.py
- tests/test_descriptors.py
This add partial documentation testing for descriptors.py, and full documentation for parameters.py.
> 166 continued addition of documentation and testing

- firecrown/connector/__init__.py
- firecrown/connector/cobaya/ccl.py
- firecrown/connector/cobaya/likelihood.py
- firecrown/connector/cosmosis/likelihood.py
- firecrown/descriptors.py
- firecrown/likelihood/likelihood.py
This PR contains more documentation and other pylint-related cleanup.
> 178 more linting cleanup

- examples/srd_sn/README.md
> README file formatting correction

- examples/cosmicshear/cosmicshear.py
- examples/des_y1_3x2pt/des_y1_3x2pt.py
- examples/srd_sn/generate_sn_data.py
- examples/srd_sn/sn_srd.py
Fixes merge collisions issues with the current state of the `master` branch.
> Am610 sn newbrnach 1

- .github/workflows/ci.yml
- docs/developer_installation.rst
- environment.yml
> Update instructions and environment.yml

- examples/cosmicshear/generate_cosmicshear_data.py
- firecrown/__init__.py
- firecrown/likelihood/gauss_family/gauss_family.py
- firecrown/likelihood/gauss_family/statistic/statistic.py
- firecrown/likelihood/gauss_family/statistic/supernova.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
- firecrown/utils.py
- tests/likelihood/gauss_family/statistic/test_statistic.py
- tests/test_utils.py
- tests/test_version.py
This adds `DataVector`, `TheoryVector` and `StatisticsResults`.
> 221 add classes for theory and data vectors

- .github/workflows/ci.yml
- firecrown/connector/mapping.py
- firecrown/connector/numcosmo/numcosmo.py
- firecrown/likelihood/gauss_family/statistic/source/number_counts.py
- firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
- firecrown/likelihood/gauss_family/statistic/statistic.py
- firecrown/likelihood/gauss_family/statistic/supernova.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
- firecrown/parameters.py
- firecrown/utils.py
- tests/likelihood/gauss_family/statistic/test_two_point.py
- tests/test_parameters.py
- tests/test_pyccl.py
> 223 more pylint application

- firecrown/likelihood/gauss_family/statistic/source/number_counts.py
- firecrown/likelihood/gauss_family/statistic/source/source.py
- firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
This fixes more complaints about variable names.
> Fix some pylint variable name complaints

- examples/des_y1_3x2pt/des_y1_3x2pt.py
- firecrown/connector/cobaya/ccl.py
- firecrown/descriptors.py
- firecrown/likelihood/gauss_family/gauss_family.py
- firecrown/likelihood/gauss_family/statistic/source/number_counts.py
- firecrown/likelihood/gauss_family/statistic/source/source.py
- firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
- firecrown/likelihood/gauss_family/statistic/statistic.py
- firecrown/likelihood/gauss_family/statistic/supernova.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
- firecrown/parameters.py
- pylintrc_for_tests
- tests/likelihood/gauss_family/statistic/source/test_source.py
- tests/test_descriptors.py
- tests/test_parameters.py
- tests/test_pt_systematics.py
- tests/test_updatable.py
Improvements to type annotations. Significant refactoring to simplify `test_pt_systematics.py`
> 229 more cleanup

- environment.yml
- examples/cosmicshear/cosmicshear.py
- examples/des_y1_3x2pt/des_y1_3x2pt.py
- examples/des_y1_3x2pt/numcosmo_run.py
- examples/des_y1_3x2pt/numcosmo_run_PT.py
- examples/srd_sn/numcosmo_run.py
- firecrown/connector/cobaya/ccl.py
- firecrown/connector/cobaya/likelihood.py
- firecrown/connector/cosmosis/likelihood.py
- firecrown/connector/mapping.py
- firecrown/connector/numcosmo/numcosmo.py
- firecrown/likelihood/gauss_family/gauss_family.py
- firecrown/likelihood/gauss_family/statistic/source/number_counts.py
- firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
- firecrown/likelihood/gauss_family/statistic/statistic.py
- firecrown/likelihood/gauss_family/statistic/supernova.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
- firecrown/likelihood/likelihood.py
- firecrown/updatable.py
- setup.cfg
- tests/connector/test_mapping.py
- tests/likelihood/gauss_family/statistic/test_statistic.py
- tests/likelihood/test_likelihood.py
We want to make more use of mypy to check the robustness of our code. This pull request turns on more of the checks that mypy can use to do so.
> Increase the strictness of mypy

- firecrown/connector/numcosmo/numcosmo.py
- setup.cfg
> Add explicit_package_bases flag for mypy

- firecrown/connector/mapping.py
- firecrown/likelihood/gauss_family/statistic/cluster_number_counts.py
- firecrown/models/cluster_abundance.py
- firecrown/models/cluster_mass.py
- firecrown/models/cluster_mass_rich_proxy.py
- firecrown/models/cluster_redshift.py
- pylintrc
- tests/pylintrc
> Still more pylint

- .github/workflows/ci.yml
- README.md
> Activate coverage report

- firecrown/version.py
- setup.cfg
- setup.py
- tests/test_version.py
This is a basic setuptools configuration update. We should assess whether and when to transition to using pyproject.toml.
> Updated setup.py and moved all options and metadata to setup.cfg

- firecrown/version.py
- tests/test_version.py
- tutorial/intro_article.qmd
> Change version number to 1.6.1a0

- .github/workflows/ci.yml
- examples/des_y1_3x2pt/numcosmo_run.py
- firecrown/connector/numcosmo/numcosmo.py
- setup.cfg
Fixed package name in setup.cfg.
Debugging mypy.
> Fixing mypy issues

- firecrown/likelihood/gauss_family/gauss_family.py
- tests/likelihood/gauss_family/test_const_gaussian.py
> Add decorator implementation of state machine

- .github/workflows/ci.yml
- codecov.yml
- environment.yml
- firecrown/likelihood/gauss_family/statistic/binned_cluster_number_counts.py
This PR contains the new codecov configuration needed to replace coveralls with codecov.  
This closes #357
> Adding codecov coverage tool to CI

- environment.yml
This commit requires numcosmo < 0.21.0
> Require numcosmo < 0.21.0

- firecrown/likelihood/gauss_family/statistic/two_point.py
- tests/test_pt_systematics.py
> 368 theoretical prediction breaking with certain bandpower windows

- docs/conf.py
- docs/environment.yml
Updated the conf file with the required changes.
> Updating readthedocs to use the fancy sphinx book theme.

- tests/test_bug_413.py
This adds a test that demonstrates the bug in TwoPoint.calcuate_pk.
> Add new, failing, test to demo the bug

- firecrown/likelihood/gauss_family/gauss_family.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
- firecrown/models/cluster/binning.py
- tests/likelihood/gauss_family/test_const_gaussian.py
- tests/test_bug_413.py
This will close issue #413 . It also simplifies the `__eq__` for `TupleBin` and fixes some flake8 complaints.
> Fix bug 413 and friends

- firecrown/__init__.py
- firecrown/connector/cosmosis/likelihood.py
- firecrown/connector/mapping.py
- firecrown/connector/numcosmo/numcosmo.py
- firecrown/likelihood/gauss_family/gauss_family.py
- firecrown/likelihood/gauss_family/gaussian.py
- firecrown/likelihood/gauss_family/statistic/source/number_counts.py
- firecrown/likelihood/gauss_family/statistic/source/source.py
- firecrown/likelihood/gauss_family/statistic/source/weak_lensing.py
- firecrown/likelihood/gauss_family/statistic/supernova.py
- firecrown/likelihood/gauss_family/statistic/two_point.py
- firecrown/likelihood/gauss_family/student_t.py
- firecrown/likelihood/likelihood.py
- firecrown/metadata/two_point.py
- firecrown/modeling_tools.py
- firecrown/updatable.py
This applies a few commits, each of which includes refactorings to simplify code.
No changes of behavior are introduced.
> Simplify refactorings

- firecrown/connector/numcosmo/numcosmo.py
This updates the docstrings in the connector for NumCosmo.
> Update numcosmo connector docstrings

- firecrown/likelihood/two_point.py
- tests/test_pt_systematics.py
This PR finishes moving theory-related instance variables from the class `TwoPoint` into the class `TwoPointTheory`. It is another step (but not the end) of the refactoring of `TwoPoint`.
Please delete options that are not relevant.
> More refactoring of TwoPoint statistic

- .gitignore
- firecrown/generators/inferred_galaxy_zdist.py
- tests/generators/test_inferred_galaxy_zdist.py
- tutorial/inferred_zdist_generators.qmd
- tutorial/inferred_zdist_serialization.qmd
Adding correct source binning.
Updated tutorials.
Fixes #454 
* New feature (non-breaking change which adds functionality)
> Fixing LSST SRD binning

- examples/des_y1_3x2pt/factory_PT.py
- firecrown/data_types.py
- firecrown/likelihood/binned_cluster_number_counts.py
- firecrown/likelihood/statistic.py
- firecrown/likelihood/supernova.py
- firecrown/likelihood/two_point.py
- firecrown/models/two_point.py
- tests/likelihood/gauss_family/statistic/test_statistic.py
- tests/likelihood/gauss_family/statistic/test_two_point.py
- tests/test_old_imports.py
- tests/test_pt_systematics.py
This PR contains additional refactoring of the TwoPoint module, working toward having prediction functionality moved to TwoPointTheory.
* Refactoring
- [x ] I have run `bash pre-commit-check` and fixed any issues
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] I have made corresponding changes to the documentation
> Refactoring twopoint

- .github/workflows/ci.yml
- firecrown/likelihood/two_point.py
This PR will extend our CI system to use Python 3.13. This is purely an addition.
It also fixes a type problem previously unreported by `mypy`.
* New feature (non-breaking change which adds functionality)
> Run CI using Python 3.13

- Making_a_new_release.md
- docs/conf.py
- firecrown/version.py
- tests/test_version.py
- tutorial/_quarto.yml
- tutorial/introduction_to_firecrown.qmd
- tutorial/two_point_generators.qmd
New release 1.10.0.
* New release.
> Updating version 1.9.0 => 1.10.0.

- .github/workflows/ci.yml
- environment.yml
Update of version requirements following NEP 29.
* Update requirement versions.
> Update nep29 2025-04-04

- .github/workflows/ci.yml
This PR will update our CI to use the most recent Smokescreen release, v1.5.0
* Update for CI
> Move to smokescreen 1.5.0 in CI

- .github/workflows/ci.yml
Currently the caching in the CI mixes different installations. This PR reorganizes the caching process to avoid problems with mixing versions.  
* Bug fix (non-breaking change which fixes an issue)
> Fixing CI caching issues.
